# Digital Store Bot v2 Configuration

# Bot Configuration
bot:
  token: "YOUR_BOT_TOKEN"
  domain: "yourdomain.com"
  port: 8080
  admins:
    - 123456789
  dev_id: 123456789
  support_id: 123456789

# Database Configuration
database:
  driver: "sqlite+aiosqlite"
  host: null
  port: null
  name: "digital_store"
  username: null
  password: null
  echo: false
  pool_size: 5
  max_overflow: 10

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  username: null
  password: null

# Shop Configuration
shop:
  name: "Digital Store"
  email: "support@digitalstore.com"
  currency: "USD"
  trial:
    enabled: true
    period_days: 3
    referred_enabled: true
    referred_period_days: 7
  referral:
    enabled: true
    level_one_reward_days: 10
    level_two_reward_days: 3

# Product Configuration
products:
  catalog_file: "config/products.yml"
  default_category: "digital"
  delivery_timeout_seconds: 3600
  categories:
    - software
    - gaming
    - subscription
    - digital
    - education

# Payment Configuration
payments:
  telegram_stars:
    enabled: true
  cryptomus:
    enabled: false
    api_key: "YOUR_CRYPTOMUS_API_KEY"
    merchant_id: "YOUR_CRYPTOMUS_MERCHANT_ID"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"
  file_enabled: true
  file_path: "logs/app.log"
  file_max_bytes: 10485760  # 10MB
  file_backup_count: 5

# Internationalization
i18n:
  default_locale: "en"
  locales_dir: "src/presentation/telegram/locales"
  supported_locales:
    - en
    - ru
    - zh

# Security
security:
  secret_key: "YOUR_SECRET_KEY"
  token_expire_hours: 24
  max_requests_per_minute: 60

# External Services
external:
  webhook_url: null  # Set for webhook mode
  webhook_secret: null